require 'oauth2'
require 'byebug'
require 'active_support/all'

require 'linkedin/version'
require 'linkedin/error'
require 'linkedin/utils'
require 'linkedin/api/authentication'
require 'linkedin/configuration'
require 'linkedin/client'
