module LinkedIn
  module API
    module Industries
      def self.all
        INDUSTRIES
      end

      def self.[](code)
        find_by_code(code)
      end

      def self.find_by_code(code)
        INDUSTRIES.detect { |indust| indust[:code] == code }
      end

      def self.find_by_group(*groups)
        INDUSTRIES.reject { |indust| (groups & indust[:group]) != groups }
      end

      def self.find_by_description(description)
        INDUSTRIES.detect { |indust| indust[:description].to_s.downcase == description.to_s.downcase }
      end

      INDUSTRIES = [ { code: 1,   group: [:gov, :tech],         description: 'Defense & Space' },
                     { code: 3,   group: [:tech],               description: 'Computer Hardware' },
                     { code: 4,   group: [:tech],               description: 'Computer Software' },
                     { code: 5,   group: [:tech],               description: 'Computer Networking' },
                     { code: 6,   group: [:tech],               description: 'Internet' },
                     { code: 7,   group: [:tech],               description: 'Semiconductors' },
                     { code: 8,   group: [:gov, :tech],         description: 'Telecommunications' },
                     { code: 9,   group: [:leg],                description: 'Law Practice' },
                     { code: 10,  group: [:leg],                description: 'Legal Services' },
                     { code: 11,  group: [:corp],               description: 'Management Consulting' },
                     { code: 12,  group: [:gov, :hlth, :tech],  description: 'Biotechnology' },
                     { code: 13,  group: [:hlth],               description: 'Medical Practice' },
                     { code: 14,  group: [:hlth],               description: 'Hospital & Health Care' },
                     { code: 15,  group: [:hlth, :tech],        description: 'Pharmaceuticals' },
                     { code: 16,  group: [:hlth],               description: 'Veterinary' },
                     { code: 17,  group: [:hlth],               description: 'Medical Devices' },
                     { code: 18,  group: [:good],               description: 'Cosmetics' },
                     { code: 19,  group: [:good],               description: 'Apparel & Fashion' },
                     { code: 20,  group: [:good, :rec],         description: 'Sporting Goods' },
                     { code: 21,  group: [:good],               description: 'Tobacco' },
                     { code: 22,  group: [:good],               description: 'Supermarkets' },
                     { code: 23,  group: [:good, :man, :serv],  description: 'Food Production' },
                     { code: 24,  group: [:good, :man],         description: 'Consumer Electronics' },
                     { code: 25,  group: [:good, :man],         description: 'Consumer Goods' },
                     { code: 26,  group: [:good, :man],         description: 'Furniture' },
                     { code: 27,  group: [:good, :man],         description: 'Retail' },
                     { code: 28,  group: [:med, :rec],          description: 'Entertainment' },
                     { code: 29,  group: [:rec],                description: 'Gambling & Casinos' },
                     { code: 30,  group: [:rec, :serv, :tran],  description: 'Leisure, Travel & Tourism' },
                     { code: 31,  group: [:rec, :serv, :tran],  description: 'Hospitality' },
                     { code: 32,  group: [:rec, :serv],         description: 'Restaurants' },
                     { code: 33,  group: [:rec],                description: 'Sports' },
                     { code: 34,  group: [:rec, :serv],         description: 'Food & Beverages' },
                     { code: 35,  group: [:art, :med, :rec],    description: 'Motion Pictures and Film' },
                     { code: 36,  group: [:med, :rec],          description: 'Broadcast Media' },
                     { code: 37,  group: [:art, :med, :rec],    description: 'Museums and Institutions' },
                     { code: 38,  group: [:art, :med, :rec],    description: 'Fine Art' },
                     { code: 39,  group: [:art, :med, :rec],    description: 'Performing Arts' },
                     { code: 40,  group: [:rec, :serv],         description: 'Recreational Facilities and Services' },
                     { code: 41,  group: [:fin],                description: 'Banking' },
                     { code: 42,  group: [:fin],                description: 'Insurance' },
                     { code: 43,  group: [:fin],                description: 'Financial Services' },
                     { code: 44,  group: [:cons, :fin, :good],  description: 'Real Estate' },
                     { code: 45,  group: [:fin],                description: 'Investment Banking' },
                     { code: 46,  group: [:fin],                description: 'Investment Management' },
                     { code: 47,  group: [:corp, :fin],         description: 'Accounting' },
                     { code: 48,  group: [:cons],               description: 'Construction' },
                     { code: 49,  group: [:cons],               description: 'Building Materials' },
                     { code: 50,  group: [:cons],               description: 'Architecture & Planning' },
                     { code: 51,  group: [:cons, :gov],         description: 'Civil Engineering' },
                     { code: 52,  group: [:gov, :man],          description: 'Aviation & Aerospace' },
                     { code: 53,  group: [:man],                description: 'Automotive' },
                     { code: 54,  group: [:man],                description: 'Chemicals' },
                     { code: 55,  group: [:man],                description: 'Machinery' },
                     { code: 56,  group: [:man],                description: 'Mining & Metals' },
                     { code: 57,  group: [:man],                description: 'Oil & Energy' },
                     { code: 58,  group: [:man],                description: 'Shipbuilding' },
                     { code: 59,  group: [:man],                description: 'Utilities' },
                     { code: 60,  group: [:man],                description: 'Textiles' },
                     { code: 61,  group: [:man],                description: 'Paper & Forest Products' },
                     { code: 62,  group: [:man],                description: 'Railroad Manufacture' },
                     { code: 63,  group: [:agr],                description: 'Farming' },
                     { code: 64,  group: [:agr],                description: 'Ranching' },
                     { code: 65,  group: [:agr],                description: 'Dairy' },
                     { code: 66,  group: [:agr],                description: 'Fishery' },
                     { code: 67,  group: [:edu],                description: 'Primary/Secondary Education' },
                     { code: 68,  group: [:edu],                description: 'Higher Education' },
                     { code: 69,  group: [:edu],                description: 'Education Management' },
                     { code: 70,  group: [:edu, :gov],          description: 'Research' },
                     { code: 71,  group: [:gov],                description: 'Military' },
                     { code: 72,  group: [:gov, :leg],          description: 'Legislative Office' },
                     { code: 73,  group: [:gov, :leg],          description: 'Judiciary' },
                     { code: 74,  group: [:gov],                description: 'International Affairs' },
                     { code: 75,  group: [:gov],                description: 'Government Administration' },
                     { code: 76,  group: [:gov],                description: 'Executive Office' },
                     { code: 77,  group: [:gov, :leg],          description: 'Law Enforcement' },
                     { code: 78,  group: [:gov],                description: 'Public Safety' },
                     { code: 79,  group: [:gov],                description: 'Public Policy' },
                     { code: 80,  group: [:corp, :med],         description: 'Marketing and Advertising' },
                     { code: 81,  group: [:med, :rec],          description: 'Newspapers' },
                     { code: 82,  group: [:med, :rec],          description: 'Publishing' },
                     { code: 83,  group: [:med, :rec],          description: 'Printing' },
                     { code: 84,  group: [:med, :serv],         description: 'Information Services' },
                     { code: 85,  group: [:med, :rec, :serv],   description: 'Libraries' },
                     { code: 86,  group: [:org, :serv],         description: 'Environmental Services' },
                     { code: 87,  group: [:serv, :tran],        description: 'Package/Freight Delivery' },
                     { code: 88,  group: [:org, :serv],         description: 'Individual & Family Services' },
                     { code: 89,  group: [:org, :serv],         description: 'Religious Institutions' },
                     { code: 90,  group: [:org, :serv],         description: 'Civic & Social Organization' },
                     { code: 91,  group: [:org, :serv],         description: 'Consumer Services' },
                     { code: 92,  group: [:tran],               description: 'Transportation/Trucking/Railroad' },
                     { code: 93,  group: [:tran],               description: 'Warehousing' },
                     { code: 94,  group: [:man, :tech, :tran],  description: 'Airlines/Aviation' },
                     { code: 95,  group: [:tran],               description: 'Maritime' },
                     { code: 96,  group: [:tech],               description: 'Information Technology and Services' },
                     { code: 97,  group: [:corp],               description: 'Market Research' },
                     { code: 98,  group: [:corp],               description: 'Public Relations and Communications' },
                     { code: 99,  group: [:art, :med],          description: 'Design' },
                     { code: 100, group: [:org],                description: 'Non-Profit Organization Management' },
                     { code: 101, group: [:org],                description: 'Fund-Raising' },
                     { code: 102, group: [:corp, :org],         description: 'Program Development' },
                     { code: 103, group: [:art, :med, :rec],    description: 'Writing and Editing' },
                     { code: 104, group: [:corp],               description: 'Staffing and Recruiting' },
                     { code: 105, group: [:corp],               description: 'Professional Training & Coaching' },
                     { code: 106, group: [:fin, :tech],         description: 'Venture Capital & Private Equity' },
                     { code: 107, group: [:gov, :org],          description: 'Political Organization' },
                     { code: 108, group: [:corp, :gov, :serv],  description: 'Translation and Localization' },
                     { code: 109, group: [:med, :rec],          description: 'Computer Games' },
                     { code: 110, group: [:corp, :rec, :serv],  description: 'Events Services' },
                     { code: 111, group: [:art, :med, :rec],    description: 'Arts and Crafts' },
                     { code: 112, group: [:good, :man],         description: 'Electrical/Electronic Manufacturing' },
                     { code: 113, group: [:med],                description: 'Online Media' },
                     { code: 114, group: [:gov, :man, :tech],   description: 'Nanotechnology' },
                     { code: 115, group: [:art, :rec],          description: 'Music' },
                     { code: 116, group: [:corp, :tran],        description: 'Logistics and Supply Chain' },
                     { code: 117, group: [:man],                description: 'Plastics' },
                     { code: 118, group: [:tech],               description: 'Computer & Network Security' },
                     { code: 119, group: [:tech],               description: 'Wireless' },
                     { code: 120, group: [:leg, :org],          description: 'Alternative Dispute Resolution' },
                     { code: 121, group: [:corp, :org, :serv],  description: 'Security and Investigations' },
                     { code: 122, group: [:corp, :serv],        description: 'Facilities Services' },
                     { code: 123, group: [:corp],               description: 'Outsourcing/Offshoring' },
                     { code: 124, group: [:hlth, :rec],         description: 'Health, Wellness and Fitness' },
                     { code: 125, group: [:hlth],               description: 'Alternative Medicine' },
                     { code: 126, group: [:med, :rec],          description: 'Media Production' },
                     { code: 127, group: [:art, :med],          description: 'Animation' },
                     { code: 128, group: [:cons, :corp, :fin],  description: 'Commercial Real Estate' },
                     { code: 129, group: [:fin],                description: 'Capital Markets' },
                     { code: 130, group: [:gov, :org],          description: 'Think Tanks' },
                     { code: 131, group: [:org],                description: 'Philanthropy' },
                     { code: 132, group: [:edu, :org],          description: 'E-Learning' },
                     { code: 133, group: [:good],               description: 'Wholesale' },
                     { code: 134, group: [:corp, :good, :tran], description: 'Import and Export' },
                     { code: 135, group: [:cons, :gov, :man],   description: 'Mechanical or Industrial Engineering' },
                     { code: 136, group: [:art, :med, :rec],    description: 'Photography' },
                     { code: 137, group: [:corp],               description: 'Human Resources' },
                     { code: 138, group: [:corp, :man],         description: 'Business Supplies and Equipment' },
                     { code: 139, group: [:hlth],               description: 'Mental Health Care' },
                     { code: 140, group: [:art, :med],          description: 'Graphic Design' },
                     { code: 141, group: [:gov, :org, :tran],   description: 'International Trade and Development' },
                     { code: 142, group: [:good, :man, :rec],   description: 'Wine and Spirits' },
                     { code: 143, group: [:good],               description: 'Luxury Goods & Jewelry' },
                     { code: 144, group: [:gov, :man, :org],    description: 'Renewables & Environment' },
                     { code: 145, group: [:cons, :man],         description: 'Glass, Ceramics & Concrete' },
                     { code: 146, group: [:good, :man],         description: 'Packaging and Containers' },
                     { code: 147, group: [:cons, :man],         description: 'Industrial Automation' },
                     { code: 148, group: [:gov],                description: 'Government Relations' } ]
    end
  end
end
